runtime: nodejs16



instance_class: F2


env_variables:

  DATABASE_HOST: "ID393242_portfolio.db.webhosting.be"

  NODE_ENV: "production"

  DATABASE_NAME: "ID393242_portfolio"

  DATABASE_USERNAME: "ID393242_portfolio"

  DATABASE_PASSWORD: "MARLENA1"